services:
  php:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./api/php
    networks:
      - app
    ports:
      - '9005:9000'
    volumes:
      - ./api:/var/www/html
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    networks:
      - app
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-montision}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-montision}
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: nginx/
    networks:
      - app
    ports:
      - '82:80'
    depends_on:
      - php
      - database
    volumes:
      - ./api:/var/www/html
      - ./nginx:/etc/nginx/conf.d

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
    networks:
      - app

volumes:
  db_data:

networks:
  app:
