FROM nginx:1.23

RUN echo '' > /etc/nginx/conf.d/default.conf && mkdir -p /etc/nginx/ssl /tmp/cache \
    && chown nginx:nginx /var/cache/nginx /var/run /tmp/cache

COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/dhparam.pem /etc/nginx/ssl/dhparam.pem

USER nginx
